import { Providers } from "./providers";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Landlord Crazy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="zh" className="dark">
      <body className={inter.className}>
        <Providers>
          <div className="md:w-[768px] h-screen mx-auto border border-white">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
